name: Python application

on:
  push:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
      run: python3 main.py
